name = "tbcube"
version = "0.1.0"
license = ""
description = "Cube file generation for extended tight-binding methods"

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"
tblite.git = "https://github.com/haneug/tblite"
tblite.branch = "spgfn"
